### ISSUE TITLE
Can't open local pdf's

### ISSUE THREAD

**Issue by Shane-Lester** [ManKeomorakort/ionic3-benchmark#1]
Hi,
I tried using your code to view local pdf's but I can't get it to work.
I put a pdf in the Home directory and changed 
this.pdfUrl = './firebase.pdf';

but nothing comes up

Any idea how to get this working (I'm really struggling to get an Ionic pdf viewer working)?

Shane

**Comment by mankeomorakort** [comment]
try to move your pdf to assets folder and change this.pdfUrl = "./assets/firebase.pdf";

**Comment by Shane-Lester** [comment]
That worked, thanks



On 8 Aug 2017, at 04:07, Keomorakort.Man <notifications@github.com<mailto:notifications@github.com>> wrote:


try to move your pdf to assets folder and change this.pdfUrl = "./assets/firebase.pdf";

**Comment by xtof974** [comment]
I have the same issue. With Ionic serve command, the pdf is displayed but on my android device i have a blank screen with local pdf. 

I put my pdf in that folder src/assets/mypdf.pdf and change this.pdfUrl = "./assets/mypdf.pdf";

could you help me ?
